using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

public static class Debug
{
    static Dictionary<byte, string> instructionMap = new Dictionary<byte, string>
    {
        { 0x00, "BRK" },
        { 0x01, "ORA (Indirect, X)" },
        { 0x05, "ORA Zero Page" },
        { 0x06, "ASL Zero Page" },
        { 0x08, "PHP" },
        { 0x09, "ORA Immediate" },
        { 0x0A, "ASL Accumulator" },
        { 0x0D, "ORA Absolute" },
        { 0x0E, "ASL Absolute" },
        { 0x10, "BPL Relative" },
        { 0x11, "ORA (Indirect), Y" },
        { 0x15, "ORA Zero Page, X" },
        { 0x16, "ASL Zero Page, X" },
        { 0x18, "CLC" },
        { 0x19, "ORA Absolute, Y" },
        { 0x1D, "ORA Absolute, X" },
        { 0x1E, "ASL Absolute, X" },
        { 0x20, "JSR Absolute" },
        { 0x21, "AND (Indirect, X)" },
        { 0x24, "BIT Zero Page" },
        { 0x25, "AND Zero Page" },
        { 0x26, "ROL Zero Page" },
        { 0x28, "PLP" },
        { 0x29, "AND Immediate" },
        { 0x2A, "ROL Accumulator" },
        { 0x2C, "BIT Absolute" },
        { 0x2D, "AND Absolute" },
        { 0x2E, "ROL Absolute" },
        { 0x30, "BMI Relative" },
        { 0x31, "AND (Indirect), Y" },
        { 0x35, "AND Zero Page, X" },
        { 0x36, "ROL Zero Page, X" },
        { 0x38, "SEC" },
        { 0x39, "AND Absolute, Y" },
        { 0x3D, "AND Absolute, X" },
        { 0x3E, "ROL Absolute, X" },
        { 0x40, "RTI" },
        { 0x41, "EOR (Indirect, X)" },
        { 0x45, "EOR Zero Page" },
        { 0x46, "LSR Zero Page" },
        { 0x48, "PHA" },
        { 0x49, "EOR Immediate" },
        { 0x4A, "LSR Accumulator" },
        { 0x4C, "JMP Absolute" },
        { 0x4D, "EOR Absolute" },
        { 0x4E, "LSR Absolute" },
        { 0x50, "BVC Relative" },
        { 0x51, "EOR (Indirect), Y" },
        { 0x55, "EOR Zero Page, X" },
        { 0x56, "LSR Zero Page, X" },
        { 0x58, "CLI" },
        { 0x59, "EOR Absolute, Y" },
        { 0x5D, "EOR Absolute, X" },
        { 0x5E, "LSR Absolute, X" },
        { 0x60, "RTS" },
        { 0x61, "ADC (Indirect, X)" },
        { 0x65, "ADC Zero Page" },
        { 0x66, "ROR Zero Page" },
        { 0x68, "PLA" },
        { 0x69, "ADC Immediate" },
        { 0x6A, "ROR Accumulator" },
        { 0x6C, "JMP (Indirect)" },
        { 0x6D, "ADC Absolute" },
        { 0x6E, "ROR Absolute" },
        { 0x70, "BVS Relative" },
        { 0x71, "ADC (Indirect), Y" },
        { 0x75, "ADC Zero Page, X" },
        { 0x76, "ROR Zero Page, X" },
        { 0x78, "SEI" },
        { 0x79, "ADC Absolute, Y" },
        { 0x7D, "ADC Absolute, X" },
        { 0x7E, "ROR Absolute, X" },
        { 0x81, "STA (Indirect, X)" },
        { 0x84, "STY Zero Page" },
        { 0x85, "STA Zero Page" },
        { 0x86, "STX Zero Page" },
        { 0x88, "DEY" },
        { 0x8A, "TXA" },
        { 0x8C, "STY Absolute" },
        { 0x8D, "STA Absolute" },
        { 0x8E, "STX Absolute" },
        { 0x90, "BCC Relative" },
        { 0x91, "STA (Indirect), Y" },
        { 0x94, "STY Zero Page, X" },
        { 0x95, "STA Zero Page, X" },
        { 0x96, "STX Zero Page, Y" },
        { 0x98, "TYA" },
        { 0x99, "STA Absolute, Y" },
        { 0x9A, "TXS" },
        { 0x9D, "STA Absolute, X" },
        { 0xA0, "LDY Immediate" },
        { 0xA1, "LDA (Indirect, X)" },
        { 0xA2, "LDX Immediate" },
        { 0xA4, "LDY Zero Page" },
        { 0xA5, "LDA Zero Page" },
        { 0xA6, "LDX Zero Page" },
        { 0xA8, "TAY" },
        { 0xA9, "LDA Immediate" },
        { 0xAA, "TAX" },
        { 0xAC, "LDY Absolute" },
        { 0xAD, "LDA Absolute" },
        { 0xAE, "LDX Absolute" },
        { 0xB0, "BCS Relative" },
        { 0xB1, "LDA (Indirect), Y" },
        { 0xB4, "LDY Zero Page, X" },
        { 0xB5, "LDA Zero Page, X" },
        { 0xB6, "LDX Zero Page, Y" },
        { 0xB8, "CLV" },
        { 0xB9, "LDA Absolute, Y" },
        { 0xBA, "TSX" },
        { 0xBC, "LDY Absolute, X" },
        { 0xBD, "LDA Absolute, X" },
        { 0xBE, "LDX Absolute, Y" },
        { 0xC0, "CPY Immediate" },
        { 0xC1, "CMP (Indirect, X)" },
        { 0xC4, "CPY Zero Page" },
        { 0xC5, "CMP Zero Page" },
        { 0xC6, "DEC Zero Page" },
        { 0xC8, "INY" },
        { 0xC9, "CMP Immediate" },
        { 0xCA, "DEX" },
        { 0xCC, "CPY Absolute" },
        { 0xCD, "CMP Absolute" },
        { 0xCE, "DEC Absolute" },
        { 0xD0, "BNE Relative" },
        { 0xD1, "CMP (Indirect), Y" },
        { 0xD5, "CMP Zero Page, X" },
        { 0xD6, "DEC Zero Page, X" },
        { 0xD8, "CLD" },
        { 0xD9, "CMP Absolute, Y" },
        { 0xDD, "CMP Absolute, X" },
        { 0xDE, "DEC Absolute, X" },
        { 0xE0, "CPX Immediate" },
        { 0xE1, "SBC (Indirect, X)" },
        { 0xE4, "CPX Zero Page" },
        { 0xE5, "SBC Zero Page" },
        { 0xE6, "INC Zero Page" },
        { 0xE8, "INX" },
        { 0xE9, "SBC Immediate" },
        { 0xEA, "NOP" },
        { 0xEC, "CPX Absolute" },
        { 0xED, "SBC Absolute" },
        { 0xEE, "INC Absolute" },
        { 0xF0, "BEQ Relative" },
        { 0xF1, "SBC (Indirect), Y" },
        { 0xF5, "SBC Zero Page, X" },
        { 0xF6, "INC Zero Page, X" },
        { 0xF8, "SED" },
        { 0xF9, "SBC Absolute, Y" },
        { 0xFD, "SBC Absolute, X" },
        { 0xFE, "INC Absolute, X" }
    };

    public static string OpToStr(byte opcode)
    {
        if (instructionMap.TryGetValue(opcode, out string mnemonic))
        {
            return mnemonic;
        }

        return "???"; // Unknown opcode
    }
}
